## Q1

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,21,(3,3))
arr

array([[11, 18, 14],
       [ 9,  3,  5],
       [13, 13,  5]])

## Q2

In [13]:
arr=np.random.rand(5,5)
print(arr)
row_min=np.max(arr,1)
print(row_min)
row_max=np.min(arr,1)

[[0.63947953 0.13997931 0.72991654 0.31335793 0.57409224]
 [0.8907406  0.12884367 0.26684813 0.25690647 0.66463187]
 [0.99716648 0.57492636 0.54661944 0.67282383 0.34046808]
 [0.42692265 0.84178765 0.15988194 0.19355459 0.71465325]
 [0.42691754 0.16103616 0.5543148  0.15976525 0.24035295]]
[0.72991654 0.8907406  0.99716648 0.84178765 0.5543148 ]


## Q3

In [22]:
arr=np.random.randint(1,100,10)
x=np.sort(arr)
print(x)

[ 8 13 21 24 26 48 58 88 89 93]


## Q4

In [5]:
import statistics as stats

In [6]:

arr=np.array([1,2,3,3,3,6,7,8])
mode=stats.mode(arr)
print(mode)


3


## Q5

In [11]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
for i in range(array_2d.shape[0]):
    for j in range(array_2d.shape[1]):
        if(array_2d[i][j]%2==0):
            array_2d[i][j]=0
        
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]
[[1 0 3 0]
 [5 0 7 0]]


## Q6

In [12]:
arr=np.array([1,4,9,16,25])
result=np.sqrt(arr)
print(result)

[1. 2. 3. 4. 5.]


## Q7

In [ ]:
arr=np.random.randint(1,21,(3,3))
print(arr)
for i in range(arr.shape[0]):   
    for j in range(arr.shape[1]):
        mean_arr=np.mean(arr[i])
        arr[i][j]=arr[i][j]-mean_arr
print(arr)

[[14  9 18]
 [13 12  5]
 [14  4 18]]
[[ 0  0 12]
 [ 3  5  0]
 [ 2 -4 12]]


## Q8

In [23]:
count=0
i=0
arr = np.empty(20)
while count !=20:
    if i %2 !=0:
        arr[count]=i
        count+=1
    i+=1
print(arr)


[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39.]


## Q9

In [25]:
arr=np.random.randint(1,101,(5,5))
print(arr)
sorted_arr=np.sort(arr,0)
ans=sorted_arr[-2,:]
print(ans)  

[[ 80  41  96  22  74]
 [ 92  83  61  94  56]
 [ 64  55 100  37 100]
 [ 66  36  34  38   6]
 [ 14  79  11  48  73]]
[80 79 96 48 74]


## Q10

In [28]:
arr=np.random.randint(1,21,(4,4))
print(arr)
sum_row=np.sum(arr,1)
print(sum_row)

[[ 5 10 20 20]
 [ 8 15 18 14]
 [11 16  8  7]
 [18 13 19  4]]
[55 55 42 54]
