## Q1

In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,21,(3,3))
arr

array([[11, 18, 14],
       [ 9,  3,  5],
       [13, 13,  5]])

## Q2

In [13]:
arr=np.random.rand(5,5)
print(arr)
row_min=np.max(arr,1)
print(row_min)
row_max=np.min(arr,1)

[[0.63947953 0.13997931 0.72991654 0.31335793 0.57409224]
 [0.8907406  0.12884367 0.26684813 0.25690647 0.66463187]
 [0.99716648 0.57492636 0.54661944 0.67282383 0.34046808]
 [0.42692265 0.84178765 0.15988194 0.19355459 0.71465325]
 [0.42691754 0.16103616 0.5543148  0.15976525 0.24035295]]
[0.72991654 0.8907406  0.99716648 0.84178765 0.5543148 ]


## Q3

In [22]:
arr=np.random.randint(1,100,10)
x=np.sort(arr)
print(x)

[ 8 13 21 24 26 48 58 88 89 93]


## Q4

In [24]:
import statistics as stats

In [25]:

arr=np.array([1,2,3,3,3,6,7,8])
mode=stats.mode(arr)
print(mode)


3


## Q5